// Package petapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package petapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xVy27bOhD9FWLuXdwLqJacFF1o10eAGmiLAM2u8IKVRhJT8RFy5Ngw9O/FUJKd2kqy",
	"aAtkZVGaxzlnztB7KKx21qChAPkeQtGglvHxynvr+cF569CTwvi6sCXyb2W9lgQ5KEOXF5AA7RwOR6zR",
	"Q5+AxhBkHaPHj4G8MjX0fQIe7zrlsYT821DzGL8+FLPfb7EgrnWNdI5FladI3ryeRWKknoORAMn6eXiq",
	"hLHEI8gGMIQ6PvzrsYIc/kmP0qajrinTYGXkdjWEL7PsUFN6L3fQc3tlKsu1WlWgCRH7wAE+r24icEUt",
	"H7/ey7pGLxgFWc8ybtAHZQ3ksFxki4yjrUMjnYIcLuOrBJykJqJNS1vwbz0IzPJKUtasymP1D7YAliQ4",
	"a8Ig/UWWDW4whCZmSudaVcTc9DZw/8lOcwr3CZQYCq8cDVjHVoyGP4ZOa+l3nDIyLCMIknXgmfBpzYGp",
	"G/WfJfBJBYoDYsZeaiT0nL8/6f7R3gstzU7EKQqywiN13ghJwhoUpDSK/7TcimWW/Q88IMjhrkO/m7yR",
	"Q6u0IkgesD5bEi23Snf617kfjNqvf1PlZ6wX5oR/K5yssRTRfcJWwg16NSjLKNYetq8MbmP709RWmR+s",
	"FjUoOCbW4iJHGslTLohoKtm19Md4DvfWDNHO4NZhQVgKHGMe+oytImTbTvwnp8Xjuk/A2TDjsPceJeHo",
	"sZPhLc8l+9K17UEceEH0Bx5CMv1z9tOipXuHtCr7x2+Mxt5fI73brcrndu6mQaFKNgu7xyGNa+cVbnBa",
	"Mb6njhsWm8PD25l8h0857C9v1JzQV5PMU2PmJcVGtorf3XUY6CVNfmUqKyrrhRTBYaEqVTxiAk5Dv5nG",
	"2fkWcmiIXJ5Gd/Af0GK8rxfKppsl9Ov+ZwAAAP//avd1x2QIAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
